export const VEHICLE_MAKE_MODELS: Record<string, string[]> = {
  Acura: ['ILX', 'Integra', 'MDX', 'NSX', 'RDX', 'RLX', 'TLX', 'ZDX'],
  'Alfa Romeo': ['4C', 'Giulia', 'Giulietta', 'MiTo', 'Stelvio', 'Tonale'],
  'Ashok Leyland': ['Bada Dost', 'Boss', 'Captain', 'Dost', 'Ecomet', 'Partner'],
  'Aston Martin': ['DB11', 'DB12', 'DBS', 'DBX', 'Rapide', 'Vantage', 'Vanquish'],
  Audi: ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'e-tron', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'R8', 'TT'],
  Bajaj: ['Avenger', 'Boxer', 'CT 100', 'Discover', 'Dominar', 'Platina', 'Pulsar', 'Qute'],
  Bentley: ['Bentayga', 'Continental GT', 'Flying Spur', 'Mulsanne'],
  Benelli: ['302S', '502C', 'Leoncino', 'TRK 502', 'TNT 600'],
  BMW: ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '7 Series', '8 Series', 'i3', 'i4', 'i7', 'i8', 'iX', 'M3', 'M4', 'M5', 'X1', 'X3', 'X5', 'X6', 'X7', 'Z4'],
  'BMW Motorrad': ['C 400', 'F 750 GS', 'F 850 GS', 'G 310 GS', 'G 310 R', 'R 1250 GS', 'R nineT', 'S 1000 RR'],
  Buick: ['Enclave', 'Encore', 'Envision', 'LaCrosse', 'Regal'],
  BYD: ['Atto 3', 'Dolphin', 'Han', 'Seal', 'Sealion', 'Song Plus', 'Tang', 'Yuan Plus'],
  Cadillac: ['CT4', 'CT5', 'Escalade', 'Lyriq', 'XT4', 'XT5', 'XT6'],
  Changan: ['Alsvin', 'CS35', 'CS55', 'CS75', 'Hunter', 'Oshan X7'],
  Chery: ['Arrizo 5', 'Arrizo 8', 'QQ', 'Tiggo 2', 'Tiggo 4', 'Tiggo 7', 'Tiggo 8'],
  Chevrolet: ['Aveo', 'Blazer', 'Camaro', 'Captiva', 'Colorado', 'Corvette', 'Cruze', 'Equinox', 'Malibu', 'Silverado', 'Spark', 'Suburban', 'Tahoe', 'Trailblazer', 'Trax'],
  Chrysler: ['200', '300', 'Pacifica', 'PT Cruiser', 'Voyager'],
  Citroen: ['Berlingo', 'C1', 'C3', 'C4', 'C5 Aircross', 'C-Elysee', 'Jumpy'],
  'CF Moto': ['250 NK', '300 NK', '450 SR', '650 MT', '800 MT'],
  Dacia: ['Duster', 'Jogger', 'Logan', 'Sandero', 'Spring'],
  DAF: ['CF', 'LF', 'XF', 'XG'],
  Daihatsu: ['Boon', 'Copen', 'Hijet', 'Mira', 'Move', 'Rocky', 'Terios', 'YRV'],
  Dodge: ['Challenger', 'Charger', 'Durango', 'Grand Caravan', 'Journey', 'Ram Van'],
  Ducati: ['Diavel', 'Hypermotard', 'Monster', 'Multistrada', 'Panigale', 'Scrambler', 'Streetfighter'],
  Eicher: ['Pro 2049', 'Pro 3015', 'Pro 6028', 'Skyline', 'Starline'],
  Ferrari: ['296', '488', '812', 'California', 'F8', 'Portofino', 'Purosangue', 'Roma', 'SF90'],
  Fiat: ['500', '500X', 'Doblo', 'Ducato', 'Panda', 'Punto', 'Tipo'],
  Ford: ['Bronco', 'EcoSport', 'Edge', 'Escape', 'Everest', 'Expedition', 'Explorer', 'F-150', 'Fiesta', 'Focus', 'Mustang', 'Ranger', 'Transit'],
  'Force Motors': ['Gurkha', 'Traveller', 'Trax', 'Urbania'],
  Freightliner: ['Cascadia', 'M2', 'SD', 'Sprinter'],
  Fuso: ['Canter', 'Fighter', 'Rosa', 'Super Great'],
  GAC: ['Emkoo', 'Empow', 'GA4', 'GA8', 'GS3', 'GS4', 'GS8', 'M8'],
  Geely: ['Azkarra', 'Coolray', 'Emgrand', 'Geometry C', 'Monjaro', 'Okavango'],
  Genesis: ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
  GMC: ['Acadia', 'Canyon', 'Hummer EV', 'Savana', 'Sierra', 'Terrain', 'Yukon'],
  'Great Wall': ['Cannon', 'Haval H6', 'Haval Jolion', 'Ora Good Cat', 'Poer', 'Tank 300'],
  'Harley-Davidson': ['Breakout', 'Fat Boy', 'Iron 883', 'Pan America', 'Sportster', 'Street Glide'],
  Haval: ['Dargo', 'F7', 'H2', 'H6', 'H9', 'Jolion'],
  Hero: ['Destini', 'Glamour', 'HF Deluxe', 'Karizma', 'Maestro', 'Passion', 'Pleasure', 'Splendor', 'Xtreme'],
  Hino: ['300 Series', '500 Series', '700 Series', 'Dutro', 'Poncho'],
  Honda: ['Accord', 'BR-V', 'City', 'Civic', 'CR-V', 'Fit', 'HR-V', 'Insight', 'Jazz', 'Odyssey', 'Pilot', 'Ridgeline', 'Vezel', 'WR-V'],
  'Honda Motorcycle': ['Africa Twin', 'CB Hornet', 'CBR', 'Dio', 'Gold Wing', 'PCX', 'Rebel', 'Shine', 'Unicorn', 'X-ADV'],
  Hongqi: ['E-HS9', 'H5', 'H7', 'H9', 'HS5', 'HS7'],
  Hummer: ['H1', 'H2', 'H3', 'EV Pickup', 'EV SUV'],
  Husqvarna: ['701 Enduro', '701 Supermoto', 'Norden 901', 'Svartpilen 250', 'Svartpilen 401', 'Vitpilen 401'],
  Hyundai: ['Accent', 'Atos', 'Azera', 'Creta', 'Elantra', 'Grand i10', 'i10', 'i20', 'i30', 'Kona', 'Palisade', 'Santa Fe', 'Sonata', 'Staria', 'Tucson', 'Venue'],
  Infiniti: ['EX', 'FX', 'G', 'Q30', 'Q50', 'Q60', 'Q70', 'QX30', 'QX50', 'QX60', 'QX80'],
  'Indian Motorcycle': ['Chief', 'Chieftain', 'FTR', 'Roadmaster', 'Scout', 'Springfield'],
  Isuzu: ['D-Max', 'Elf', 'F-Series', 'MU-X', 'N-Series', 'Trooper'],
  Iveco: ['Daily', 'Eurocargo', 'S-Way', 'Stralis', 'Trakker'],
  JAC: ['J7', 'JS4', 'JS6', 'M3', 'T6', 'T8'],
  Jaguar: ['E-Pace', 'F-Pace', 'F-Type', 'I-Pace', 'XE', 'XF', 'XJ'],
  Jeep: ['Cherokee', 'Compass', 'Gladiator', 'Grand Cherokee', 'Renegade', 'Wrangler'],
  Kawasaki: ['KLR 650', 'Ninja 300', 'Ninja 400', 'Ninja 650', 'Ninja ZX-10R', 'Versys 650', 'Vulcan S', 'Z900'],
  Kenworth: ['T680', 'T880', 'W900'],
  Kia: ['Carnival', 'Ceed', 'Cerato', 'K5', 'K8', 'Niro', 'Picanto', 'Rio', 'Seltos', 'Sorento', 'Soul', 'Sportage', 'Stinger', 'Telluride'],
  KGM: ['Actyon', 'Korando', 'Musso', 'Rexton', 'Tivoli', 'Torres'],
  KTM: ['125 Duke', '200 Duke', '250 Duke', '390 Duke', '790 Adventure', 'RC 200', 'RC 390'],
  Lamborghini: ['Aventador', 'Countach', 'Gallardo', 'Huracan', 'Revuelto', 'Urus'],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'],
  Lexus: ['CT', 'ES', 'GS', 'GX', 'IS', 'LC', 'LS', 'LX', 'NX', 'RC', 'RX', 'UX'],
  Li: ['L6', 'L7', 'L8', 'L9', 'Mega'],
  Lincoln: ['Aviator', 'Continental', 'Corsair', 'MKC', 'MKX', 'Navigator', 'Nautilus'],
  Lucid: ['Air', 'Gravity'],
  Mack: ['Anthem', 'Granite', 'MD', 'Pinnacle'],
  Mahindra: ['Bolero', 'KUV100', 'Marazzo', 'Pik-Up', 'Scorpio', 'Thar', 'XUV300', 'XUV500', 'XUV700'],
  MAN: ['TGE', 'TGL', 'TGM', 'TGS', 'TGX'],
  Maserati: ['Ghibli', 'GranTurismo', 'Grecale', 'Levante', 'MC20', 'Quattroporte'],
  Mazda: ['2', '3', '6', 'BT-50', 'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-60', 'CX-8', 'CX-9', 'MX-5', 'RX-8'],
  McLaren: ['570S', '600LT', '720S', '750S', 'Artura', 'GT', 'Senna'],
  'Mercedes-Benz': ['A-Class', 'B-Class', 'C-Class', 'CLA', 'CLS', 'E-Class', 'G-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'S-Class', 'Sprinter', 'V-Class'],
  MG: ['3', '4', '5', 'Astor', 'Gloster', 'Hector', 'HS', 'Marvel R', 'MG ZS', 'ZS EV'],
  Mini: ['Clubman', 'Convertible', 'Cooper', 'Countryman', 'Paceman'],
  Mitsubishi: ['Attrage', 'Eclipse Cross', 'L200', 'Lancer', 'Mirage', 'Montero', 'Outlander', 'Pajero', 'Triton'],
  Nissan: ['Almera', 'Altima', 'Armada', 'Frontier', 'GT-R', 'Juke', 'Kicks', 'Leaf', 'March', 'Navara', 'Patrol', 'Qashqai', 'Rogue', 'Sentra', 'Sunny', 'X-Trail'],
  Nio: ['EC6', 'EC7', 'ES6', 'ES7', 'ES8', 'ET5', 'ET7'],
  Opel: ['Astra', 'Combo', 'Corsa', 'Crossland', 'Grandland', 'Insignia', 'Mokka', 'Vivaro', 'Zafira'],
  Peugeot: ['108', '2008', '208', '3008', '308', '408', '5008', '508', 'Boxer', 'Expert', 'Partner'],
  Peterbilt: ['337', '389', '520', '579'],
  Piaggio: ['Ape', 'Beverly', 'Liberty', 'Medley', 'Porter'],
  Porsche: ['718 Boxster', '718 Cayman', '911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
  Proton: ['Exora', 'Iriz', 'Persona', 'Saga', 'Satria', 'X50', 'X70', 'X90'],
  Ram: ['1500', '2500', '3500', 'ProMaster'],
  Renault: ['Arkana', 'Captur', 'Clio', 'Duster', 'Kangoo', 'Kiger', 'Koleos', 'Kwid', 'Megane', 'Trafic', 'Zoe'],
  Rivian: ['R1S', 'R1T', 'EDV'],
  'Rolls-Royce': ['Cullinan', 'Dawn', 'Ghost', 'Phantom', 'Spectre', 'Wraith'],
  'Royal Enfield': ['Bullet', 'Classic 350', 'Continental GT', 'Himalayan', 'Hunter 350', 'Interceptor', 'Meteor'],
  Saab: ['9-3', '9-5', '900', '9000'],
  Scania: ['G-Series', 'K-Series', 'L-Series', 'P-Series', 'R-Series', 'S-Series'],
  SEAT: ['Arona', 'Ateca', 'Ibiza', 'Leon', 'Tarraco'],
  Skoda: ['Citigo', 'Enyaq', 'Fabia', 'Karoq', 'Kodiaq', 'Octavia', 'Rapid', 'Scala', 'Superb'],
  Smart: ['Forfour', 'Fortwo', 'Smart #1', 'Smart #3'],
  Subaru: ['Ascent', 'BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Legacy', 'Levorg', 'Outback', 'WRX', 'XV'],
  Suzuki: ['Alto', 'Baleno', 'Celerio', 'Dzire', 'Ertiga', 'Every', 'Grand Vitara', 'Ignis', 'Jimny', 'S-Cross', 'Swift', 'Vitara', 'Wagon R'],
  Tata: ['Altroz', 'Harrier', 'Indica', 'Indigo', 'Nexon', 'Punch', 'Safari', 'Sumo', 'Tiago', 'Tigor', 'Xenon'],
  Tesla: ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster', 'Semi'],
  Toyota: ['Alphard', 'Aqua', 'Avalon', 'Avanza', 'Camry', 'Corolla', 'Crown', 'Fortuner', 'Harrier', 'Hiace', 'Hilux', 'Land Cruiser', 'Noah', 'Prius', 'RAV4', 'Vellfire', 'Vitz', 'Yaris'],
  Triumph: ['Bonneville', 'Rocket 3', 'Scrambler', 'Speed Triple', 'Street Triple', 'Tiger', 'Trident'],
  TVS: ['Apache', 'Jupiter', 'NTorq', 'Raider', 'Ronin', 'Scooty Pep', 'Sport', 'Star City'],
  UD: ['Condor', 'Croner', 'Kazet', 'Quester'],
  Vauxhall: ['Astra', 'Combo', 'Corsa', 'Crossland', 'Grandland', 'Mokka', 'Vivaro'],
  Vespa: ['GTS', 'LX', 'Primavera', 'Sprint'],
  Volkswagen: ['Amarok', 'Arteon', 'Caddy', 'Golf', 'ID.3', 'ID.4', 'Jetta', 'Passat', 'Polo', 'T-Cross', 'T-Roc', 'Tiguan', 'Touareg', 'Transporter'],
  Volvo: ['C40', 'S60', 'S90', 'V40', 'V60', 'V90', 'XC40', 'XC60', 'XC90'],
  'Volvo Trucks': ['FH', 'FL', 'FM', 'FMX', 'VNL', 'VNR'],
  Wuling: ['Air EV', 'Almaz', 'Cortez', 'Hongguang Mini EV'],
  Xpeng: ['G3', 'G6', 'G9', 'P5', 'P7', 'X9'],
  Yamaha: ['Aerox', 'FZ', 'MT-07', 'MT-09', 'NMAX', 'R15', 'R3', 'RayZR', 'Tenere 700', 'XMAX', 'YZF-R1'],
  Zeekr: ['001', '007', '009', 'X'],
};

export const VEHICLE_BRANDS = Object.keys(VEHICLE_MAKE_MODELS).sort((a, b) => a.localeCompare(b));

export const VEHICLE_MODELS = Array.from(
  new Set(Object.values(VEHICLE_MAKE_MODELS).flat()),
).sort((a, b) => a.localeCompare(b));

export function getVehicleModels(make?: string) {
  if (!make) return VEHICLE_MODELS;
  return VEHICLE_MAKE_MODELS[make] ?? [];
}
